export const ESCAPE_DURATION_SEC = 1800;

const SCENE_DETAILS = {
  newspaper1896:{image:"/public/escape/01-newspaper-1896.png",scene:"무거운 나무문을 밀자 오래된 종이와 잉크 냄새가 훅 끼쳐 와요. 천장까지 닿은 서랍장에서 신문들이 바람도 없는데 한 장씩 빠져나와 날아다니고, 방 한가운데 분류대에는 서로 모습이 다른 기사 세 장이 놓여 있어요. 맞은편 출구의 황동 시간자물쇠는 기사들이 올바른 기록함에 들어가기를 기다리며 낮게 째깍거립니다."},
  empire1902:{image:"/public/escape/02-empire-score-1902.png",scene:"신문방의 자물쇠가 열리자 금빛 장식이 번지는 황실 음악 보관실로 이어져요. 검푸른 비단 탁자 위에는 악보 표지가 네 조각으로 찢겨 있고, 주변의 금관악기들은 아무도 건드리지 않았는데 낮은 음을 웅웅 울려요. 자개장 중앙의 잠금쇠에는 조각난 악보와 작곡가 기록을 올바른 순서로 복원하라는 표시가 떠올라요."},
  chanmiga:{image:"/public/escape/03-chanmiga-library.png",scene:"좁은 회랑 끝에서 두 갈래 빛이 비치는 서가가 나타나요. 왼쪽과 오른쪽 독서대에는 닮은 『찬미가』 두 권이 놓였지만 표지의 인장과 기록 연도가 서로 달라, 어느 한쪽을 치우면 다른 책이 더 밝게 빛나요. 공중에 뜬 의문노트가 두 책 사이를 오가며 하나를 없애지 말고 기록의 차이를 보라는 듯 빈 페이지를 펼칩니다."},
  oldMelody:{image:"/public/escape/04-old-melody-corridor.png",scene:"서가 뒤 비밀문을 통과하자 긴 석조 복도 바닥에 세 갈래 음표 길이 흐르기 시작해요. 앞쪽의 가사 카드들은 푸른 선율과 붉은 선율 사이에서 방향을 잃었고, 왼편 음악상자에서는 낯설지만 익숙한 스코틀랜드풍 멜로디가 희미하게 들려요. 어두운 쪽 장구 길은 막혀 있으므로 가사 카드가 실제로 따라갔던 곡조 길을 연결해야 다음 문이 열립니다."},
  song1935:{image:"/public/escape/05-chicago-1935.png",scene:"복도 끝 문을 열자 겨울밤의 시카고가 보이는 작은 한인 연주홀이 펼쳐져요. 피아노 옆에서는 연주자들이 새 선율을 맞춰 보고 있고, 지휘대 앞 탁자에는 빛나는 기록 블록 세 개와 시대가 다른 가짜 블록 하나가 섞여 있어요. 연주는 첫 마디에서 계속 멈추고 있으니 연도·작곡가·사건을 정확히 배열해 새 곡의 기록을 완성해야 해요."},
  approval1941:{image:"/public/escape/06-provisional-government-1941.png",scene:"연주가 완성되는 순간 무대 뒤편이 충칭의 임시정부 사무실로 바뀌어요. 책상 위 공보와 새 곡보는 붉은 끈으로 묶여 있고, 옆에는 의미가 다른 나무도장 세 개가 잉크패드 앞에 가지런히 놓여 있어요. 잘못된 도장을 찍으면 문서가 잠겨 버리므로 새 곡을 공식적으로 사용할 수 있게 하는 도장을 찾아야 합니다."},
  record1942:{image:"/public/escape/07-record-workshop-1942.png",scene:"승인 도장이 빛나자 벽장이 열리고 기계음이 가득한 레코드공방이 나타나요. 중앙 회전판의 검은 음반에는 서로 다른 두 색의 홈이 나란히 새겨져 있지만 라벨 자리는 비어 있고, 낡은 축음기는 바늘을 올리지 못한 채 빙글빙글 돌아가요. 옛 곡조와 새 곡조가 함께 남은 사실을 찾아 두 라벨을 모두 완성해야 재생 손잡이가 풀립니다."},
  chongqing1945:{image:"/public/escape/08-chongqing-printshop-1945.png",scene:"축음기의 마지막 소리를 따라가면 새벽빛이 들어오는 충칭의 인쇄소에 도착해요. 인쇄기에서는 악보가 계속 나오지만 한국어·중국어·영어 페이지가 빨랫줄과 제본대에 뒤섞여 책으로 묶이지 못하고 있어요. 발행 연도를 맨 앞에 두고 세 언어 페이지를 올바른 순서로 모아야 출판 상자 속 열쇠를 얻을 수 있습니다."},
  spread1948:{image:"/public/escape/09-textbook-distribution-1948.png",scene:"제본된 악보 상자를 밀자 바닥 전체가 커다란 한반도 지도로 변해요. 지도 가장자리에는 교과서 수레들이 멈춰 서 있고 학교 모형, 공식 행사장, 개인 주택, 먼 외국 박물관으로 이어지는 길들이 서로 얽혀 있어요. 애국가가 전국의 어린이와 시민에게 퍼질 수 있도록 실제 보급의 중심이 된 두 장소에 수레를 보내야 합니다."},
  committee1955:{image:"/public/escape/10-committee-1955.png",scene:"지도 위 마지막 수레가 도착하자 빗소리가 들리는 조사위원회 회의실로 이동해요. 긴 회의가 끝난 듯 의자들은 비어 있고, 탁자에는 두 후보의 두꺼운 서류철과 증거가 채워지지 않은 열린 기록철이 남아 있어요. 벽의 증거판은 붉은 실이 중간에서 끊겨 있으므로, 없는 자료를 만들어 내지 않고 조사 결과를 정직하게 기록해야 해요."},
  ceremony1984:{image:"/public/escape/11-ceremony-hall-1984.png",scene:"조사위원회 뒤편의 보너스 문을 열면 서로 다른 두 행사장이 반씩 나뉜 강당이 보여요. 왼쪽은 붉은 융단과 단상이 마련된 큰 공식 행사장이고, 오른쪽은 의자와 작은 연단만 놓인 소규모 행사장이에요. 바닥의 절차 카드가 뒤섞여 있으니 행사 규모에 맞는 정식·약식 절차를 각각 찾아야 숨은 기록함이 열립니다."},
  heritage2020:{image:"/public/escape/12-heritage-vault-2020.png",scene:"강당의 숨은 승강기가 차갑고 조용한 현대 문화유산 보존실에 멈춰요. 유리 보관함 안의 오래된 대한제국 애국가 악보는 금빛 조명을 받고 있고, 작업대에는 장갑·라벨·습도표·보존 상자와 함께 일반 풀과 맨손 경고가 섞여 있어요. 악보를 훼손하지 않을 네 가지 항목만 골라 마지막 기록 조각을 안전하게 봉인해야 합니다."}
};

const ESCAPE_ROOM_BASE = [
  { id:"newspaper1896",icon:"📰",year:"1896",title:"신문방",guide:"기록할머니: 애국가가 처음부터 딱 하나였을까? 기사 제목과 가사를 살펴보렴.",certainty:"resolved",mechanic:"drag",prompt:"기사를 눌러 내용을 읽은 뒤 알맞은 기록함으로 옮기세요.",fact:"『독립신문』에는 제목은 애국가지만 가사가 서로 다른 여러 노래가 실렸어요.",items:[
    {id:"a",label:"5월 19일 애국가 원문",date:"1896년 5월 19일",section:"2면 2단",headline:"인쳔 졔물포 뎐경 국가",original:["봉츅세 봉츅 아국태평 봉츅세","즐겁도다 즐겁도 독립쥬 즐겁도다","퓌여라 퓌여 우리명산 퓌여라","향기롭다 향기롭 우리국가 향기롭다","열열나 열열 부국강병 열열나","열심세 열심 츙군국 열심세","진력세 진력 롱공샹 진력세","빗나도다 빗나도 우리국긔 빗나도다","영화롭다 영화롭 우리만민 영화롭다","놉흐시다 놉흐시 우리님군 놉흐시다","만셰만셰 만만셰 대군쥬폐하 만만셰","쟝셩 기운으 셰계이 유명야 텬하각국 넘볼세라"],translation:["봉축하세 봉축하세 우리나라의 평안을 축하하세","즐겁도다 즐겁도다 자주독립이 즐겁도다","꽃피어라 꽃피어라 우리 명산에 꽃피어라","향기롭다 향기롭다 우리나라가 향기롭다","열매 열라 열매 열라 부국강병의 열매 열라","열심히 하세 열심히 하세 나라 사랑을 열심히 하세","온 힘을 다하세 온 힘을 다해 모든 백성이 힘쓰세","빛나도다 빛나도다 우리 국기가 빛나도다","영화롭다 영화롭다 우리 모든 백성이 영화롭다","높으시다 높으시다 우리 임금 높으시다","만세 만세 만만세 대군주 폐하 만만세","힘찬 기운으로 세계에 이름을 떨쳐 다른 나라가 넘보지 못하리라"],vocabulary:["봉축: 경사스러운 일을 축하함","아국: 우리나라","진력: 온 힘을 다함","사농공상: 농민·기술자·상인 등 여러 직업의 백성"],clue:"전경택이 지은 가사로, 다른 두 원문과 구절이 달라요.",sourceUrl:"https://nl.go.kr/newspaper/detail.do?content_id=CNTS-00098985651"},
    {id:"b",label:"7월 4일 애국가 원문",date:"1896년 7월 4일",section:"2면 3단",headline:"누통 한명원 국가",original:["텬디구샹 륙쥬즁 쥬독립 분명다","경향원근 무론고 을여 진보세","츙셩으로 보국세 사마다 셔로세","평안시졀 양병여 셰계샹에 횡세","경보기 무란니 합심통덕 첫로다","몸이 비록 쥭드 나라위 을마세","강이 깁고 산이 놉되 우리음 반길일세"," 만만셰를 불너 우리 님군 봉츅세"],translation:["세상의 여섯 대륙 가운데 자주독립이 분명하다","서울과 지방, 가깝고 먼 곳을 가리지 말고 깨어나 발전하세","충성으로 나라의 은혜를 갚자고 사람마다 맹세하세","평안할 때 군대를 길러 세계에 당당히 나아가세","경사를 보기가 어렵지 않으니 마음을 합치는 일이 첫째로다","몸이 비록 죽더라도 나라를 위한 일을 한스럽게 여기지 마세","강이 깊고 산이 높듯 우리 마음도 반길 일이로다","함께 만만세를 불러 우리 임금을 축하하세"],vocabulary:["육주: 세계의 여섯 대륙","경향원근: 서울과 지방의 가깝고 먼 모든 곳","보국: 나라의 은혜를 갚음","합심: 여러 사람이 마음을 하나로 모음"],clue:"한명원이 지은 가사로, 자주독립과 합심을 노래해요.",sourceUrl:"https://nl.go.kr/newspaper/detail.do?content_id=CNTS-00098986136"},
    {id:"c",label:"9월 5일 애국가 원문",date:"1896년 9월 5일",section:"2면 2단",headline:"평양 학당 김죵셥 국가",original:["광활 텬디간 우리인 삼겨나셔","죠션국에 쟝여 의지식지 여시니","부모은혜 망극즁 님금은혜 더옥크다","대쟝부의 당당 츙효밧긔 잇가","삼각산 긔 죠션왕긔 쟝시고","오여년 지낸후 깃분쇼식 잇고나","반갑고도 죠흘시 쥬독립 죠흘시고","태극긔를 놉히들어 국가를 불너보셰","우리나라 대쇼인 츙군국 여보셰","먹고입고 살묘 롱공샹 힘을쓰고","듯고보고 거 효뎨츙신 본을밧셰","국태평과 민안락 날과로 츅슈셰","만셰만셰 만만셰 우리 셩쥬 억만셰"],translation:["넓은 세상에 우리 인생이 태어나","조선에서 자라며 부모를 의지하고 스승에게 배웠으니","부모의 은혜가 끝없이 크지만 임금의 은혜는 더욱 크다","당당한 사람이 할 일로 충성과 효도보다 더한 것이 있는가","삼각산의 빼어난 기운처럼 조선 왕조의 기운도 굳세고","오백여 년이 지난 뒤 기쁜 소식이 또 있구나","반갑고도 좋구나 자주독립이 좋구나","태극기를 높이 들어 애국가를 불러 보세","우리나라 어른과 아이 모두 나라 사랑을 실천해 보세","먹고 입고 살 방법으로 여러 직업에서 힘을 쓰고","듣고 보고 실천할 일은 효도와 믿음을 본받는 것이네","나라의 평안과 백성의 편안함을 날마다 기원하세","만세 만세 만만세 우리 임금 억만세"],vocabulary:["생장: 태어나서 자람","충효: 나라에 충성하고 부모를 공경함","대소인: 어른과 아이를 포함한 모든 사람","민안락: 백성이 편안하고 즐겁게 삶"],clue:"김종섭이 지은 가사로, 태극기와 애국가를 함께 언급해요.",sourceUrl:"https://nl.go.kr/newspaper/detail.do?content_id=CNTS-00098986678"}
  ],zones:[{id:"same",label:"하나의 완성된 가사"},{id:"different",label:"서로 다른 여러 가사"}],correct:{a:"different",b:"different",c:"different"},artifact:"1896 독립신문",hints:["세 기사에서 반복되지 않는 낱말을 찾아보세요.","기사마다 가사가 서로 달라요.","세 조각을 모두 ‘서로 다른 여러 가사’ 기록함에 넣으세요."]},
  { id:"empire1902",icon:"🎼",year:"1902",title:"황실악보실",guide:"한별: 흩어진 악보 표지를 순서대로 맞추면 작곡가의 이름이 나타날 거야!",certainty:"resolved",mechanic:"sequence",prompt:"악보 표지 조각을 올바른 순서로 눌러 조립하세요.",fact:"대한제국 애국가는 현재 애국가와 다른 노래이며 프란츠 에케르트가 작곡했어요.",tokens:[{id:"empire",label:"대한제국"},{id:"anthem",label:"애국가"},{id:"eckert",label:"프란츠 에케르트"},{id:"score",label:"악보 완성"}],correct:["empire","anthem","eckert","score"],artifact:"대한제국 애국가 악보",hints:["노래의 나라 이름부터 놓아 보세요.","제목 뒤에 작곡가 이름이 와요.","대한제국 → 애국가 → 프란츠 에케르트 → 악보 완성 순서예요."]},
  { id:"chanmiga",icon:"📚",year:"1905/1908",title:"찬미가서가",guide:"의문노트: 어떤 책은 1905년, 어떤 책은 1908년이라고 적혀 있어. 하나를 지우면 될까?",certainty:"contested",mechanic:"multi",prompt:"기록에서 확인해야 할 카드를 모두 선택하세요.",fact:"『찬미가』에 현행 가사 계열이 실렸으며 발행 연도는 자료에 따라 1905년 또는 1908년으로 설명돼요.",options:[{id:"1905",label:"1905년이라는 기록"},{id:"1908",label:"1908년이라는 기록"},{id:"different",label:"자료마다 다르게 적혀 있음"},{id:"one",label:"한 연도만 무조건 정답"}],correct:["1905","1908","different"],artifact:"두 갈래 찬미가 연도표",flag:"acceptedUncertaintyChanmiga",hints:["두 책의 연도를 모두 살펴보세요.","서로 다른 기록을 함께 남길 수 있어요.","1905년·1908년·자료마다 다름, 세 카드를 선택하세요."]},
  { id:"oldMelody",icon:"🎻",year:"독립운동기",title:"곡조복도",guide:"한별: 가사와 곡조가 처음부터 한 쌍이었던 것은 아니야. 올바른 연결선을 만들어 보자!",certainty:"resolved",mechanic:"sequence",prompt:"가사 카드와 당시 사용한 곡조 카드를 차례로 연결하세요.",fact:"현행 애국가 가사는 한동안 스코틀랜드 민요 「Auld Lang Syne」 곡조에 붙여 불렀어요.",tokens:[{id:"lyrics",label:"현행 애국가 가사"},{id:"auld",label:"Auld Lang Syne 곡조"},{id:"arirang",label:"아리랑 곡조"}],correct:["lyrics","auld"],artifact:"옛 곡조 연결선",hints:["먼저 가사 카드를 고르세요.","스코틀랜드 민요를 찾아보세요.","현행 가사 → Auld Lang Syne 순서예요."]},
  { id:"song1935",icon:"🎹",year:"1935",title:"시카고 연주홀",guide:"시간자물쇠: 새 곡의 세 기록 블록을 정확한 순서로 놓아라!",certainty:"resolved",mechanic:"sequence",prompt:"연도·작곡가·사건 블록을 순서대로 눌러 주세요.",fact:"안익태는 1935년 애국가의 새로운 곡을 작곡했어요.",tokens:[{id:"1935",label:"1935년"},{id:"ahn",label:"안익태"},{id:"new",label:"새 곡 작곡"},{id:"1902",label:"1902년"}],correct:["1935","ahn","new"],artifact:"1935 새 선율",hints:["연도가 가장 먼저예요.","현재 곡조를 만든 작곡가는 안익태예요.","1935년 → 안익태 → 새 곡 작곡 순서예요."]},
  { id:"approval1941",icon:"📜",year:"1941",title:"임시정부 승인실",guide:"한별: 여기 공보 문서가 보여! 어떤 도장을 찍어야 새 곡을 쓸 수 있게 될까?",certainty:"resolved",mechanic:"stamp",prompt:"1941년 공보에 알맞은 도장을 찍으세요.",fact:"대한민국 임시정부는 1941년 2월 공보로 새 곡보의 사용 허가를 알렸어요.",options:[{id:"allow",label:"사용 허가"},{id:"ban",label:"사용 금지"},{id:"discard",label:"기록 폐기"}],correct:"allow",artifact:"임시정부 허가 공보",hints:["새 곡을 사용할 수 있게 하는 도장이에요.","금지의 반대말을 찾아보세요.","‘사용 허가’ 도장을 누르세요."]},
  { id:"record1942",icon:"💿",year:"1942",title:"레코드공방",guide:"기록할머니: 한 음반 안에 옛 곡조와 새 곡조의 흔적이 함께 남아 있단다.",certainty:"resolved",mechanic:"multi",prompt:"유성기 음반에 함께 넣을 라벨을 모두 선택하세요.",fact:"1942년 유성기 음반에는 옛 곡조의 애국가와 새 곡조의 애국가가 함께 수록됐어요.",options:[{id:"old",label:"구 애국가(옛 곡조)"},{id:"new",label:"신 애국가(새 곡조)"},{id:"only",label:"새 곡조 하나만"}],correct:["old","new"],artifact:"신·구 애국가 음반",hints:["라벨이 한 장이 아니에요.","옛 곡과 새 곡이 함께 존재했어요.","구 애국가와 신 애국가를 모두 선택하세요."]},
  { id:"chongqing1945",icon:"🖨️",year:"1945",title:"충칭출판소",guide:"한별: 여러 나라 사람이 함께 읽을 수 있도록 악보 페이지를 순서대로 묶어 보자!",certainty:"resolved",mechanic:"sequence",prompt:"발행 연도와 세 언어 페이지를 올바른 순서로 조립하세요.",fact:"1945년 충칭판 「한국애국가」 악보에는 한국어·중국어·영어 가사가 함께 실렸어요.",tokens:[{id:"1945",label:"1945년"},{id:"ko",label:"한국어"},{id:"zh",label:"중국어"},{id:"en",label:"영어"},{id:"jp",label:"일본어만"}],correct:["1945","ko","zh","en"],artifact:"충칭판 한국애국가",hints:["발행 연도를 먼저 놓으세요.","세 언어 페이지가 필요해요.","1945년 → 한국어 → 중국어 → 영어 순서예요."]},
  { id:"spread1948",icon:"🗺️",year:"1948",title:"교과서 배포실",guide:"시간자물쇠: 애국가가 전국으로 퍼질 수 있도록 두 곳에 기록 상자를 배달하라!",certainty:"resolved",mechanic:"multi",prompt:"지도에서 반드시 배달해야 할 장소를 모두 선택하세요.",fact:"정부 수립 이후 애국가는 학교와 공식 행사를 통해 전국에 널리 보급됐어요.",options:[{id:"school",label:"학교"},{id:"ceremony",label:"공식 행사장"},{id:"home",label:"한 사람의 집만"},{id:"abroad",label:"외국 박물관만"}],correct:["school","ceremony"],artifact:"1948 전국 보급 지도",hints:["많은 어린이와 시민이 모이는 곳이에요.","배움의 장소와 국가 행사가 열리는 장소예요.","학교와 공식 행사장을 선택하세요."]},
  { id:"committee1955",icon:"🔎",year:"1955",title:"조사위원회실",guide:"기록할머니: 기록이 모자라면 섣불리 한 사람으로 정하면 안 돼.",certainty:"unresolved",mechanic:"choice",prompt:"작사자 조사 회의 카드에 가장 올바른 결론을 남기세요.",fact:"1955년 작사자 조사가 있었지만 결정적인 자료가 부족해 결론을 내리지 못했어요.",options:[{id:"yun",label:"윤치호로 확정"},{id:"ahn",label:"안창호로 확정"},{id:"open",label:"아직 확정되지 않음"}],correct:"open",artifact:"열린 의문 노트",flag:"acceptedUnresolvedLyricist",hints:["회의는 열렸지만 결론이 나지 않았어요.","후보 이름보다 결정적인 자료가 있는지 생각하세요.","‘아직 확정되지 않음’을 선택하세요."]},
  { id:"ceremony1984",icon:"🏛️",year:"1984 · 보너스",title:"국민의례강당",guide:"한별: 행사 규모에 맞는 국민의례 카드를 모두 찾아 보너스 기록을 열자!",certainty:"resolved",mechanic:"multi",bonus:true,prompt:"올바른 행사 절차 카드 두 장을 선택하세요.",fact:"1984년 애국가 제창이 규정에 명문화됐고 오늘날 정식·약식 절차가 사용돼요.",options:[{id:"formal",label:"정식 행사: 정식 절차"},{id:"simple",label:"소규모 행사: 약식 절차"},{id:"none",label:"모든 행사에서 애국가 생략"}],correct:["formal","simple"],artifact:"1984 국민의례 카드",hints:["행사 규모가 서로 달라요.","정식과 약식 절차가 모두 있어요.","정식 행사와 소규모 행사 카드를 선택하세요."]},
  { id:"heritage2020",icon:"🧤",year:"2020 · 보너스",title:"문화유산보관함",guide:"기록할머니: 오래된 악보를 안전하게 보관할 도구만 골라 주렴.",certainty:"resolved",mechanic:"multi",bonus:true,prompt:"보존 상자에 넣을 네 가지 항목을 모두 선택하세요.",fact:"2020년 「대한제국애국가」가 국가등록문화유산으로 등록됐어요.",options:[{id:"score",label:"대한제국 애국가 악보"},{id:"gloves",label:"보존 장갑"},{id:"label",label:"기록 라벨"},{id:"humidity",label:"습도표"},{id:"glue",label:"일반 풀"},{id:"hands",label:"맨손"}],correct:["score","gloves","label","humidity"],artifact:"2020 문화유산 보존함",hints:["악보를 상하게 하지 않는 도구를 골라요.","장갑·라벨·습도 관리가 필요해요.","악보·장갑·라벨·습도표를 선택하세요."]}
];

export const ESCAPE_ROOMS = ESCAPE_ROOM_BASE.map(room=>{
  const detail=SCENE_DETAILS[room.id];
  return {
    ...room,
    ...detail,
    prompt:`<span class="escape-scene-visual"><img src="${detail.image}" alt="${room.title} 방탈출 장면" loading="eager"><span class="escape-scene-caption"><b>장면 속으로</b><span>${detail.scene}</span></span></span><span class="escape-room-mission"><b>이번 방의 임무</b><span>${room.prompt}</span></span>`
  };
});

export function newEscapeGame(){return{started:false,roomIndex:0,roomSolved:false,score:0,historicalTrust:100,hintsUsed:0,mistakeCount:0,roomMistakes:0,artifacts:[],flags:{acceptedUncertaintyChanmiga:false,acceptedUnresolvedLyricist:false},feedback:null,hintLevel:0,startedAt:null,interaction:{selected:[],sequence:[],placements:{},held:null,openedItem:null},forcedEnding:null}}
export function normalizeEscapeGame(value){const base=newEscapeGame();return{...base,...value,flags:{...base.flags,...value?.flags},interaction:{...base.interaction,...value?.interaction}}}
export function finalEscapeScore(game){return Math.max(10,Math.min(20,Math.round(game.score/120*16)+4))}
export function endingFor(game){if(game.forcedEnding||game.historicalTrust<=0)return["기록 혼선","시간이 끝났거나 기록 신뢰도가 모두 사라졌어요. 안내를 따라 다시 복원할 수 있어요.","⚠️"];if(game.flags.acceptedUncertaintyChanmiga&&game.flags.acceptedUnresolvedLyricist)return["열린 역사 탐정","정답뿐 아니라 기록의 차이와 아직 모르는 사실까지 존중했어요.","🔎"];if(game.score>=85&&game.historicalTrust>=80&&game.artifacts.length>=10)return["기록수호자","흩어진 기록을 정확하게 이어 시간보관소를 지켰어요.","🏛️"];return["배운 탐험가","도움을 받아 기록을 복원하며 중요한 역사를 배웠어요.","🧭"]}

function selected(game,id){return game.interaction.selected.includes(id)}
function roomMechanic(room,game){
  if(room.mechanic==="drag"){
    const opened=room.items.find(x=>x.id===game.interaction.openedItem);
    const article=opened?`<article class="archive-article-detail" aria-live="polite"><header class="archive-masthead"><span>THE INDEPENDENT</span><b>독 립 신 문</b><span>1896</span></header><div class="archive-paper-meta"><span>${opened.date}</span><span>${opened.section}</span></div><h3>${opened.headline}</h3><div class="archive-parallel-head"><span>原文 · 원문</span><span>현대어 번역</span></div><div class="archive-parallel-text">${opened.original.map((line,index)=>`<div class="archive-line-pair"><p>${line}</p><p>${opened.translation[index]}</p></div>`).join("")}</div><aside class="archive-vocabulary"><b>옛말 풀이</b><ul>${opened.vocabulary.map(word=>`<li>${word}</li>`).join("")}</ul></aside><div class="archive-clue"><b>🔎 분류 단서</b><span>${opened.clue}</span></div><a class="archive-source" href="${opened.sourceUrl}" target="_blank" rel="noreferrer">국립중앙도서관 대한민국 신문 아카이브에서 원문 확인 ↗</a><small>※ 왼쪽은 신문 아카이브의 원문 표기를 보존하고 행갈이와 띄어쓰기만 정리했습니다. 오른쪽은 초등학생이 이해하기 쉽게 옮긴 현대어 번역입니다.</small></article>`:`<div class="archive-read-guide">기사를 하나씩 눌러 실제 신문 원문과 번역을 함께 확인하세요.</div>`;
    return `<div class="archive-drag-items">${room.items.map(x=>`<button draggable="true" aria-expanded="${game.interaction.openedItem===x.id}" class="archive-card ${game.interaction.placements[x.id]?"placed":""} ${game.interaction.openedItem===x.id?"opened":""}" data-drag-item="${x.id}"><span>📰 ${x.label}</span><small>눌러서 기사 읽기</small></button>`).join("")}</div>${article}<div class="archive-dropzones">${room.zones.map(z=>`<button class="drop-zone" data-drop-zone="${z.id}"><b>${z.label}</b><small>${Object.entries(game.interaction.placements).filter(([,zone])=>zone===z.id).map(([id])=>room.items.find(x=>x.id===id)?.label).join(" · ")||"여기에 놓기"}</small></button>`).join("")}</div>`;
  }
  if(room.mechanic==="sequence")return `<div class="sequence-answer">${game.interaction.sequence.length?game.interaction.sequence.map(id=>`<span>${room.tokens.find(x=>x.id===id)?.label}</span>`).join(" → "):"조각을 순서대로 눌러 주세요"}</div><div class="token-grid">${room.tokens.map(x=>`<button class="puzzle-token ${game.interaction.sequence.includes(x.id)?"selected":""}" data-escape-token="${x.id}">${x.label}</button>`).join("")}</div><button class="btn small secondary" data-action="clear-escape-selection">순서 다시 놓기</button>`;
  if(room.mechanic==="stamp")return `<div class="stamp-grid">${room.options.map(x=>`<button class="stamp ${selected(game,x.id)?"selected":""}" data-escape-choice="${x.id}">${x.label}</button>`).join("")}</div>`;
  return `<div class="escape-choice-grid">${room.options.map(x=>`<button class="quiz-option ${selected(game,x.id)?"selected":""}" data-escape-toggle="${x.id}">${x.label}</button>`).join("")}</div>`;
}

export function renderEscape(game){
  if(!game.started)return `<div class="escape-intro"><div class="archive-door">⌛</div><span class="eyebrow">30분 기록 복원 작전</span><h2>시간보관소와 사라진 애국가 기록</h2><p class="lead">큰일 났어! 애국가 역사 기록이 열두 개의 방으로 흩어졌어. 기록도우미 한별과 함께 조각을 모아 기억의 악보문을 다시 열어 줘!</p><div class="story-box"><b>기록수호자의 약속</b><p>기록이 서로 다르면 차이를 인정하고, 확실하지 않은 사실은 억지로 단정하지 않아요.</p></div><button class="btn primary" data-action="start-escape">기록 복원 시작 →</button></div>`;
  if(game.roomIndex>=ESCAPE_ROOMS.length||game.forcedEnding){const ending=endingFor(game);return `<div class="escape-ending"><div style="font-size:76px">${ending[2]}</div><span class="eyebrow">게임 점수 ${game.score} · 기록 신뢰도 ${game.historicalTrust} · 조각 ${game.artifacts.length}/12</span><h2>${ending[0]} 엔딩</h2><p class="lead">${ending[1]}</p><div class="artifact-shelf">${game.artifacts.map(x=>`<span class="artifact-chip">✓ ${x}</span>`).join("")}</div><div class="story-box"><h3>오늘 복원한 세 가지 기록</h3><p>① 애국가는 여러 기록을 거쳐 형성되었어요.<br>② 옛날에는 지금과 다른 곡조로도 불렀어요.<br>③ 작사자는 아직 확정되지 않았어요.</p></div><div class="button-row" style="justify-content:center"><button class="btn secondary" data-action="reset-escape">다시 도전</button><button class="btn primary" data-action="finish-escape">탐험 정리 →</button></div></div>`}
  const room=ESCAPE_ROOMS[game.roomIndex];const certainty=room.certainty==="contested"?"자료마다 달라요":room.certainty==="unresolved"?"아직 확정되지 않았어요":"확인된 기록";
  return `<div class="escape-hud"><span>⏱ <b id="escape-time">30:00</b></span><span>기록 조각 <b>${game.artifacts.length}/12</b></span><span>점수 <b>${game.score}</b></span><span>신뢰도 <b>${game.historicalTrust}</b></span><button class="btn small secondary" data-action="reset-escape">처음부터</button></div><div class="escape-progress"><i style="width:${(game.roomIndex+1)/ESCAPE_ROOMS.length*100}%"></i></div><div class="room-scene"><div class="room-icon">${room.icon}</div><div><span class="badge ${room.certainty==="resolved"?"skilled":"expert"}">${room.year} · ${certainty}</span><h2>${game.roomIndex+1}번째 방 · ${room.title}</h2><p class="lead">${room.prompt}</p></div></div><div class="guide-dialog">${room.guide}</div><div class="fact-note"><b>📎 복원할 기록</b><p>${room.fact}</p></div>${roomMechanic(room,game)}${game.hintLevel?`<div class="feedback no">💡 힌트 ${game.hintLevel}: ${room.hints[game.hintLevel-1]}</div>`:""}${game.feedback?`<div class="feedback ${game.feedback.ok?"ok":"no"}">${game.feedback.text}</div>`:""}<div class="button-row"><button class="btn secondary" data-action="escape-hint" ${game.roomSolved||game.hintLevel>=3?"disabled":""}>힌트 보기 (${game.hintLevel}/3)</button>${!game.roomSolved?`<button class="btn coral" data-action="submit-escape-room">기록 확인</button>`:`<button class="btn primary" data-action="next-escape-room">${game.roomIndex===ESCAPE_ROOMS.length-1?"기억의 악보문 열기":"다음 기록방"} →</button>`}</div><div class="artifact-shelf">${game.artifacts.map(x=>`<span class="artifact-chip">${x}</span>`).join("")}</div>`;
}

function arraysEqual(a,b){return a.length===b.length&&a.every((x,i)=>x===b[i])}
function setsEqual(a,b){return a.length===b.length&&a.every(x=>b.includes(x))}
export function roomIsCorrect(room,game){if(room.mechanic==="drag")return Object.entries(room.correct).every(([item,zone])=>game.interaction.placements[item]===zone);if(room.mechanic==="sequence")return arraysEqual(game.interaction.sequence,room.correct);if(room.mechanic==="stamp"||room.mechanic==="choice")return game.interaction.selected[0]===room.correct;return setsEqual(game.interaction.selected,room.correct)}
export function submitRoom(game){const room=ESCAPE_ROOMS[game.roomIndex];if(roomIsCorrect(room,game)){game.roomSolved=true;game.score=Math.min(120,game.score+10);game.artifacts.push(room.artifact);if(room.flag)game.flags[room.flag]=true;game.feedback={ok:true,text:`복원 성공! ‘${room.artifact}’ 기록 조각을 찾았어요.`};return true}game.score=Math.max(0,game.score-2);game.mistakeCount++;game.roomMistakes++;if(room.certainty!=="resolved")game.historicalTrust=Math.max(0,game.historicalTrust-8);if(game.roomMistakes>=3){game.hintLevel=3;game.feedback={ok:false,text:"세 번 틀려 구조 힌트가 열렸어요. 체크포인트에서 다시 살펴보세요."}}else game.feedback={ok:false,text:room.certainty!=="resolved"?"하나를 억지로 확정하지 말고 기록의 차이나 빈틈을 살펴보세요.":"시간자물쇠가 열리지 않았어요. 기록과 배치를 다시 확인하세요."};if(game.historicalTrust<=0)game.forcedEnding="bad_ending";return false}
export function useHint(game){const next=Math.min(3,game.hintLevel+1);if(next===game.hintLevel)return;game.hintLevel=next;game.hintsUsed++;game.score=Math.max(0,game.score-[2,4,6][next-1])}
export function nextRoom(game){game.roomIndex++;game.roomSolved=false;game.roomMistakes=0;game.feedback=null;game.hintLevel=0;game.interaction={selected:[],sequence:[],placements:{},held:null,openedItem:null}}
