export const ESCAPE_DURATION_SEC = 1800;

export const ESCAPE_ROOMS = [
  { id:"newspaper1896",icon:"📰",year:"1896",title:"신문방",guide:"기록할머니: 애국가가 처음부터 딱 하나였을까? 기사 제목과 가사를 살펴보렴.",certainty:"resolved",mechanic:"drag",prompt:"기사 조각을 알맞은 기록함으로 옮기세요.",fact:"『독립신문』에는 제목은 애국가지만 가사가 서로 다른 여러 노래가 실렸어요.",items:[{id:"a",label:"애국가 1호 기사"},{id:"b",label:"애국가 2호 기사"},{id:"c",label:"애국가 3호 기사"}],zones:[{id:"same",label:"하나의 완성된 가사"},{id:"different",label:"서로 다른 여러 가사"}],correct:{a:"different",b:"different",c:"different"},artifact:"1896 독립신문",hints:["세 기사에서 반복되지 않는 낱말을 찾아보세요.","기사마다 가사가 서로 달라요.","세 조각을 모두 ‘서로 다른 여러 가사’ 기록함에 넣으세요."]},
  { id:"empire1902",icon:"🎼",year:"1902",title:"황실악보실",guide:"한별: 흩어진 악보 표지를 순서대로 맞추면 작곡가의 이름이 나타날 거야!",certainty:"resolved",mechanic:"sequence",prompt:"악보 표지 조각을 올바른 순서로 눌러 조립하세요.",fact:"대한제국 애국가는 현재 애국가와 다른 노래이며 프란츠 에케르트가 작곡했어요.",tokens:[{id:"empire",label:"대한제국"},{id:"anthem",label:"애국가"},{id:"eckert",label:"프란츠 에케르트"},{id:"score",label:"악보 완성"}],correct:["empire","anthem","eckert","score"],artifact:"대한제국 애국가 악보",hints:["노래의 나라 이름부터 놓아 보세요.","제목 뒤에 작곡가 이름이 와요.","대한제국 → 애국가 → 프란츠 에케르트 → 악보 완성 순서예요."]},
  { id:"chanmiga",icon:"📚",year:"1905/1908",title:"찬미가서가",guide:"의문노트: 어떤 책은 1905년, 어떤 책은 1908년이라고 적혀 있어. 하나를 지우면 될까?",certainty:"contested",mechanic:"multi",prompt:"기록에서 확인해야 할 카드를 모두 선택하세요.",fact:"『찬미가』에 현행 가사 계열이 실렸으며 발행 연도는 자료에 따라 1905년 또는 1908년으로 설명돼요.",options:[{id:"1905",label:"1905년이라는 기록"},{id:"1908",label:"1908년이라는 기록"},{id:"different",label:"자료마다 다르게 적혀 있음"},{id:"one",label:"한 연도만 무조건 정답"}],correct:["1905","1908","different"],artifact:"두 갈래 찬미가 연도표",flag:"acceptedUncertaintyChanmiga",hints:["두 책의 연도를 모두 살펴보세요.","서로 다른 기록을 함께 남길 수 있어요.","1905년·1908년·자료마다 다름, 세 카드를 선택하세요."]},
  { id:"oldMelody",icon:"🎻",year:"독립운동기",title:"곡조복도",guide:"한별: 가사와 곡조가 처음부터 한 쌍이었던 것은 아니야. 올바른 연결선을 만들어 보자!",certainty:"resolved",mechanic:"sequence",prompt:"가사 카드와 당시 사용한 곡조 카드를 차례로 연결하세요.",fact:"현행 애국가 가사는 한동안 스코틀랜드 민요 「Auld Lang Syne」 곡조에 붙여 불렀어요.",tokens:[{id:"lyrics",label:"현행 애국가 가사"},{id:"auld",label:"Auld Lang Syne 곡조"},{id:"arirang",label:"아리랑 곡조"}],correct:["lyrics","auld"],artifact:"옛 곡조 연결선",hints:["먼저 가사 카드를 고르세요.","스코틀랜드 민요를 찾아보세요.","현행 가사 → Auld Lang Syne 순서예요."]},
  { id:"song1935",icon:"🎹",year:"1935",title:"시카고 연주홀",guide:"시간자물쇠: 새 곡의 세 기록 블록을 정확한 순서로 놓아라!",certainty:"resolved",mechanic:"sequence",prompt:"연도·작곡가·사건 블록을 순서대로 눌러 주세요.",fact:"안익태는 1935년 애국가의 새로운 곡을 작곡했어요.",tokens:[{id:"1935",label:"1935년"},{id:"ahn",label:"안익태"},{id:"new",label:"새 곡 작곡"},{id:"1902",label:"1902년"}],correct:["1935","ahn","new"],artifact:"1935 새 선율",hints:["연도가 가장 먼저예요.","현재 곡조를 만든 작곡가는 안익태예요.","1935년 → 안익태 → 새 곡 작곡 순서예요."]},
  { id:"approval1941",icon:"📜",year:"1941",title:"임시정부 승인실",guide:"한별: 여기 공보 문서가 보여! 어떤 도장을 찍어야 새 곡을 쓸 수 있게 될까?",certainty:"resolved",mechanic:"stamp",prompt:"1941년 공보에 알맞은 도장을 찍으세요.",fact:"대한민국 임시정부는 1941년 2월 공보로 새 곡보의 사용 허가를 알렸어요.",options:[{id:"allow",label:"사용 허가"},{id:"ban",label:"사용 금지"},{id:"discard",label:"기록 폐기"}],correct:"allow",artifact:"임시정부 허가 공보",hints:["새 곡을 사용할 수 있게 하는 도장이에요.","금지의 반대말을 찾아보세요.","‘사용 허가’ 도장을 누르세요."]},
  { id:"record1942",icon:"💿",year:"1942",title:"레코드공방",guide:"기록할머니: 한 음반 안에 옛 곡조와 새 곡조의 흔적이 함께 남아 있단다.",certainty:"resolved",mechanic:"multi",prompt:"유성기 음반에 함께 넣을 라벨을 모두 선택하세요.",fact:"1942년 유성기 음반에는 옛 곡조의 애국가와 새 곡조의 애국가가 함께 수록됐어요.",options:[{id:"old",label:"구 애국가(옛 곡조)"},{id:"new",label:"신 애국가(새 곡조)"},{id:"only",label:"새 곡조 하나만"}],correct:["old","new"],artifact:"신·구 애국가 음반",hints:["라벨이 한 장이 아니에요.","옛 곡과 새 곡이 함께 존재했어요.","구 애국가와 신 애국가를 모두 선택하세요."]},
  { id:"chongqing1945",icon:"🖨️",year:"1945",title:"충칭출판소",guide:"한별: 여러 나라 사람이 함께 읽을 수 있도록 악보 페이지를 순서대로 묶어 보자!",certainty:"resolved",mechanic:"sequence",prompt:"발행 연도와 세 언어 페이지를 올바른 순서로 조립하세요.",fact:"1945년 충칭판 「한국애국가」 악보에는 한국어·중국어·영어 가사가 함께 실렸어요.",tokens:[{id:"1945",label:"1945년"},{id:"ko",label:"한국어"},{id:"zh",label:"중국어"},{id:"en",label:"영어"},{id:"jp",label:"일본어만"}],correct:["1945","ko","zh","en"],artifact:"충칭판 한국애국가",hints:["발행 연도를 먼저 놓으세요.","세 언어 페이지가 필요해요.","1945년 → 한국어 → 중국어 → 영어 순서예요."]},
  { id:"spread1948",icon:"🗺️",year:"1948",title:"교과서 배포실",guide:"시간자물쇠: 애국가가 전국으로 퍼질 수 있도록 두 곳에 기록 상자를 배달하라!",certainty:"resolved",mechanic:"multi",prompt:"지도에서 반드시 배달해야 할 장소를 모두 선택하세요.",fact:"정부 수립 이후 애국가는 학교와 공식 행사를 통해 전국에 널리 보급됐어요.",options:[{id:"school",label:"학교"},{id:"ceremony",label:"공식 행사장"},{id:"home",label:"한 사람의 집만"},{id:"abroad",label:"외국 박물관만"}],correct:["school","ceremony"],artifact:"1948 전국 보급 지도",hints:["많은 어린이와 시민이 모이는 곳이에요.","배움의 장소와 국가 행사가 열리는 장소예요.","학교와 공식 행사장을 선택하세요."]},
  { id:"committee1955",icon:"🔎",year:"1955",title:"조사위원회실",guide:"기록할머니: 기록이 모자라면 섣불리 한 사람으로 정하면 안 돼.",certainty:"unresolved",mechanic:"choice",prompt:"작사자 조사 회의 카드에 가장 올바른 결론을 남기세요.",fact:"1955년 작사자 조사가 있었지만 결정적인 자료가 부족해 결론을 내리지 못했어요.",options:[{id:"yun",label:"윤치호로 확정"},{id:"ahn",label:"안창호로 확정"},{id:"open",label:"아직 확정되지 않음"}],correct:"open",artifact:"열린 의문 노트",flag:"acceptedUnresolvedLyricist",hints:["회의는 열렸지만 결론이 나지 않았어요.","후보 이름보다 결정적인 자료가 있는지 생각하세요.","‘아직 확정되지 않음’을 선택하세요."]},
  { id:"ceremony1984",icon:"🏛️",year:"1984 · 보너스",title:"국민의례강당",guide:"한별: 행사 규모에 맞는 국민의례 카드를 모두 찾아 보너스 기록을 열자!",certainty:"resolved",mechanic:"multi",bonus:true,prompt:"올바른 행사 절차 카드 두 장을 선택하세요.",fact:"1984년 애국가 제창이 규정에 명문화됐고 오늘날 정식·약식 절차가 사용돼요.",options:[{id:"formal",label:"정식 행사: 정식 절차"},{id:"simple",label:"소규모 행사: 약식 절차"},{id:"none",label:"모든 행사에서 애국가 생략"}],correct:["formal","simple"],artifact:"1984 국민의례 카드",hints:["행사 규모가 서로 달라요.","정식과 약식 절차가 모두 있어요.","정식 행사와 소규모 행사 카드를 선택하세요."]},
  { id:"heritage2020",icon:"🧤",year:"2020 · 보너스",title:"문화유산보관함",guide:"기록할머니: 오래된 악보를 안전하게 보관할 도구만 골라 주렴.",certainty:"resolved",mechanic:"multi",bonus:true,prompt:"보존 상자에 넣을 네 가지 항목을 모두 선택하세요.",fact:"2020년 「대한제국애국가」가 국가등록문화유산으로 등록됐어요.",options:[{id:"score",label:"대한제국 애국가 악보"},{id:"gloves",label:"보존 장갑"},{id:"label",label:"기록 라벨"},{id:"humidity",label:"습도표"},{id:"glue",label:"일반 풀"},{id:"hands",label:"맨손"}],correct:["score","gloves","label","humidity"],artifact:"2020 문화유산 보존함",hints:["악보를 상하게 하지 않는 도구를 골라요.","장갑·라벨·습도 관리가 필요해요.","악보·장갑·라벨·습도표를 선택하세요."]}
];

export function newEscapeGame(){return{started:false,roomIndex:0,roomSolved:false,score:0,historicalTrust:100,hintsUsed:0,mistakeCount:0,roomMistakes:0,artifacts:[],flags:{acceptedUncertaintyChanmiga:false,acceptedUnresolvedLyricist:false},feedback:null,hintLevel:0,startedAt:null,interaction:{selected:[],sequence:[],placements:{},held:null},forcedEnding:null}}
export function normalizeEscapeGame(value){const base=newEscapeGame();return{...base,...value,flags:{...base.flags,...value?.flags},interaction:{...base.interaction,...value?.interaction}}}
export function finalEscapeScore(game){return Math.max(10,Math.min(20,Math.round(game.score/120*16)+4))}
export function endingFor(game){if(game.forcedEnding||game.historicalTrust<=0)return["기록 혼선","시간이 끝났거나 기록 신뢰도가 모두 사라졌어요. 안내를 따라 다시 복원할 수 있어요.","⚠️"];if(game.flags.acceptedUncertaintyChanmiga&&game.flags.acceptedUnresolvedLyricist)return["열린 역사 탐정","정답뿐 아니라 기록의 차이와 아직 모르는 사실까지 존중했어요.","🔎"];if(game.score>=85&&game.historicalTrust>=80&&game.artifacts.length>=10)return["기록수호자","흩어진 기록을 정확하게 이어 시간보관소를 지켰어요.","🏛️"];return["배운 탐험가","도움을 받아 기록을 복원하며 중요한 역사를 배웠어요.","🧭"]}

function selected(game,id){return game.interaction.selected.includes(id)}
function roomMechanic(room,game){
  if(room.mechanic==="drag")return `<div class="archive-drag-items">${room.items.map(x=>`<button draggable="true" class="archive-card ${game.interaction.placements[x.id]?"placed":""}" data-drag-item="${x.id}">📰 ${x.label}</button>`).join("")}</div><div class="archive-dropzones">${room.zones.map(z=>`<button class="drop-zone" data-drop-zone="${z.id}"><b>${z.label}</b><small>${Object.entries(game.interaction.placements).filter(([,zone])=>zone===z.id).map(([id])=>room.items.find(x=>x.id===id)?.label).join(" · ")||"여기에 놓기"}</small></button>`).join("")}</div>`;
  if(room.mechanic==="sequence")return `<div class="sequence-answer">${game.interaction.sequence.length?game.interaction.sequence.map(id=>`<span>${room.tokens.find(x=>x.id===id)?.label}</span>`).join(" → "):"조각을 순서대로 눌러 주세요"}</div><div class="token-grid">${room.tokens.map(x=>`<button class="puzzle-token ${game.interaction.sequence.includes(x.id)?"selected":""}" data-escape-token="${x.id}">${x.label}</button>`).join("")}</div><button class="btn small secondary" data-action="clear-escape-selection">순서 다시 놓기</button>`;
  if(room.mechanic==="stamp")return `<div class="stamp-grid">${room.options.map(x=>`<button class="stamp ${selected(game,x.id)?"selected":""}" data-escape-choice="${x.id}">${x.label}</button>`).join("")}</div>`;
  return `<div class="escape-choice-grid">${room.options.map(x=>`<button class="quiz-option ${selected(game,x.id)?"selected":""}" data-escape-toggle="${x.id}">${x.label}</button>`).join("")}</div>`;
}

export function renderEscape(game){
  if(!game.started)return `<div class="escape-intro"><div class="archive-door">⌛</div><span class="eyebrow">30분 기록 복원 작전</span><h2>시간보관소와 사라진 애국가 기록</h2><p class="lead">큰일 났어! 애국가 역사 기록이 열두 개의 방으로 흩어졌어. 기록도우미 한별과 함께 조각을 모아 기억의 악보문을 다시 열어 줘!</p><div class="story-box"><b>기록수호자의 약속</b><p>기록이 서로 다르면 차이를 인정하고, 확실하지 않은 사실은 억지로 단정하지 않아요.</p></div><button class="btn primary" data-action="start-escape">기록 복원 시작 →</button></div>`;
  if(game.roomIndex>=ESCAPE_ROOMS.length||game.forcedEnding){const ending=endingFor(game);return `<div class="escape-ending"><div style="font-size:76px">${ending[2]}</div><span class="eyebrow">게임 점수 ${game.score} · 기록 신뢰도 ${game.historicalTrust} · 조각 ${game.artifacts.length}/12</span><h2>${ending[0]} 엔딩</h2><p class="lead">${ending[1]}</p><div class="artifact-shelf">${game.artifacts.map(x=>`<span class="artifact-chip">✓ ${x}</span>`).join("")}</div><div class="story-box"><h3>오늘 복원한 세 가지 기록</h3><p>① 애국가는 여러 기록을 거쳐 형성되었어요.<br>② 옛날에는 지금과 다른 곡조로도 불렀어요.<br>③ 작사자는 아직 확정되지 않았어요.</p></div><div class="button-row" style="justify-content:center"><button class="btn secondary" data-action="reset-escape">다시 도전</button><button class="btn primary" data-action="finish-escape">탐험 정리 →</button></div></div>`}
  const room=ESCAPE_ROOMS[game.roomIndex];const certainty=room.certainty==="contested"?"자료마다 달라요":room.certainty==="unresolved"?"아직 확정되지 않았어요":"확인된 기록";
  return `<div class="escape-hud"><span>⏱ <b id="escape-time">30:00</b></span><span>기록 조각 <b>${game.artifacts.length}/12</b></span><span>점수 <b>${game.score}</b></span><span>신뢰도 <b>${game.historicalTrust}</b></span><button class="btn small secondary" data-action="reset-escape">처음부터</button></div><div class="escape-progress"><i style="width:${(game.roomIndex+1)/ESCAPE_ROOMS.length*100}%"></i></div><div class="room-scene"><div class="room-icon">${room.icon}</div><div><span class="badge ${room.certainty==="resolved"?"skilled":"expert"}">${room.year} · ${certainty}</span><h2>${game.roomIndex+1}번째 방 · ${room.title}</h2><p class="lead">${room.prompt}</p></div></div><div class="guide-dialog">${room.guide}</div><div class="fact-note"><b>📎 복원할 기록</b><p>${room.fact}</p></div>${roomMechanic(room,game)}${game.hintLevel?`<div class="feedback no">💡 힌트 ${game.hintLevel}: ${room.hints[game.hintLevel-1]}</div>`:""}${game.feedback?`<div class="feedback ${game.feedback.ok?"ok":"no"}">${game.feedback.text}</div>`:""}<div class="button-row"><button class="btn secondary" data-action="escape-hint" ${game.roomSolved||game.hintLevel>=3?"disabled":""}>힌트 보기 (${game.hintLevel}/3)</button>${!game.roomSolved?`<button class="btn coral" data-action="submit-escape-room">기록 확인</button>`:`<button class="btn primary" data-action="next-escape-room">${game.roomIndex===ESCAPE_ROOMS.length-1?"기억의 악보문 열기":"다음 기록방"} →</button>`}</div><div class="artifact-shelf">${game.artifacts.map(x=>`<span class="artifact-chip">${x}</span>`).join("")}</div>`;
}

function arraysEqual(a,b){return a.length===b.length&&a.every((x,i)=>x===b[i])}
function setsEqual(a,b){return a.length===b.length&&a.every(x=>b.includes(x))}
export function roomIsCorrect(room,game){if(room.mechanic==="drag")return Object.entries(room.correct).every(([item,zone])=>game.interaction.placements[item]===zone);if(room.mechanic==="sequence")return arraysEqual(game.interaction.sequence,room.correct);if(room.mechanic==="stamp"||room.mechanic==="choice")return game.interaction.selected[0]===room.correct;return setsEqual(game.interaction.selected,room.correct)}
export function submitRoom(game){const room=ESCAPE_ROOMS[game.roomIndex];if(roomIsCorrect(room,game)){game.roomSolved=true;game.score=Math.min(120,game.score+10);game.artifacts.push(room.artifact);if(room.flag)game.flags[room.flag]=true;game.feedback={ok:true,text:`복원 성공! ‘${room.artifact}’ 기록 조각을 찾았어요.`};return true}game.score=Math.max(0,game.score-2);game.mistakeCount++;game.roomMistakes++;if(room.certainty!=="resolved")game.historicalTrust=Math.max(0,game.historicalTrust-8);if(game.roomMistakes>=3){game.hintLevel=3;game.feedback={ok:false,text:"세 번 틀려 구조 힌트가 열렸어요. 체크포인트에서 다시 살펴보세요."}}else game.feedback={ok:false,text:room.certainty!=="resolved"?"하나를 억지로 확정하지 말고 기록의 차이나 빈틈을 살펴보세요.":"시간자물쇠가 열리지 않았어요. 기록과 배치를 다시 확인하세요."};if(game.historicalTrust<=0)game.forcedEnding="bad_ending";return false}
export function useHint(game){const next=Math.min(3,game.hintLevel+1);if(next===game.hintLevel)return;game.hintLevel=next;game.hintsUsed++;game.score=Math.max(0,game.score-[2,4,6][next-1])}
export function nextRoom(game){game.roomIndex++;game.roomSolved=false;game.roomMistakes=0;game.feedback=null;game.hintLevel=0;game.interaction={selected:[],sequence:[],placements:{},held:null}}
